# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # container_name: mongodbx
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME: park
    #   # - MONGO_INITDB_ROOT_USERNAME=park
    #   - MONGO_INITDB_ROOT_PASSWORD: hanbeen
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
    # image: 'goals-node'
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: 
  logs: