spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;NON_KEYWORDS=USER
      username: sa
  profiles:
    include: oauth